name: Merge on lgtm label
on:
  schedule:
    - cron: '*/20 * * * *'

permissions:
  contents: write
  pull-requests: write

jobs:
  execute:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1
      - uses: ./
        with:
          jobs: lgtm
          github-token: ${{ secrets.GITHUB_TOKEN }}
          merge-method: squash
